const express = require("express");
const cors = require ("cors")
const users = require('./Users')
const logger = require('./middleware/Logger');
const keyCheck = require("./middleware/KeyCheck");

const app = express();

const corsOption = {
  origin: "http://localhost:5174"
}


const PORT = process.env.PORT || 5000;

app.use(express.json()) //the response generated by the Post call is converted to json OR Body parser middleware
app.use(cors(corsOption))
//initialize middleware
// app.use(logger)

// app.use(keyCheck)

app.get("/", (req, res) => {
  // res.send('server is running')
  res.json(users)
});

// users api routes
app.use('/api/users', require('./routes/api/users'))
app.use('/api/blogs', require('./routes/api/blogs'))
app.use('/api/sites', require('./routes/api/sites'))

// get all users
// app.get("/api/users", (req, res) => {
//   res.json(users)
// });

// get user by id
// app.get('/api/users/:id', (req, res) => {
//    const filteredUser = users.find(user => user.id === parseInt(req.params.id))
//    if(filteredUser){
//     res.json(filteredUser)
//    }
//    else{
//     res.status(400).json({msg: `nothing found of id ${req.params.id}`})
//    }
//     // res.json(users.filter(user => user.id === parseInt(req.params.id)))
// })

app.listen(PORT, () => console.log(`this is running on port ${PORT}`));
